services:
  - type: web
    name: OneBusAway API Server
    runtime: image
    image:
      url: docker.io/opentransitsoftwarefoundation/onebusaway-api-webapp:2.5.13-cs-v1.0.0
    region: oregon
    plan: standard
    numInstances: 1
    healthCheckPath: /onebusaway-api-webapp/api/where/current-time.json?key=org.onebusaway.iphone
    autoDeploy: false
    envVars:
      - key: TZ
        sync: false
      - key: GTFS_URL
        sync: false
      - key: VEHICLE_POSITIONS_URL
        sync: false
      - key: TRIP_UPDATES_URL
        sync: false
      - key: ALERTS_URL
        sync: false
      - key: FEED_API_KEY
        sync: false
      - key: FEED_API_VALUE
        sync: false
      - key: REFRESH_INTERVAL
        value: 30
      - key: AGENCY_ID
        sync: false
      - key: JDBC_USER
        sync: false
      - key: JDBC_PASSWORD
        sync: false
      - key: JDBC_URL
        sync: false
      - key: PORT
        value: 8080
    disk:
      name: Bundle
      mountPath: /bundle
      sizeGB: 1
